# Generated by Django 5.1.4 on 2025-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_colors_alter_product_seo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
