# Generated by Django 5.1.4 on 2025-02-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cupon',
                'verbose_name_plural': '               Coupons',
            },
        ),
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Admins', 'verbose_name_plural': '                  Admins'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customers', 'verbose_name_plural': '                Customers'},
        ),
        migrations.AlterModelOptions(
            name='salesrepresentativeprofile',
            options={'verbose_name': 'Sales Representives', 'verbose_name_plural': '                 Sales Representives'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': '                   All Users'},
        ),
    ]
