# Generated by Django 5.1.4 on 2025-02-20 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cupon_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Admins', 'verbose_name_plural': '                   Admins'},
        ),
        migrations.AlterModelOptions(
            name='cupon',
            options={'verbose_name': 'Cupon', 'verbose_name_plural': '                Coupons'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customers', 'verbose_name_plural': '                 Customers'},
        ),
        migrations.AlterModelOptions(
            name='salesrepresentativeprofile',
            options={'verbose_name': 'Sales Representives', 'verbose_name_plural': '                  Sales Representives'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': '                    All Users'},
        ),
        migrations.AddField(
            model_name='cupon',
            name='max_usage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CuponApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupon Applied',
                'verbose_name_plural': '               Coupons Applied',
            },
        ),
    ]
