# Generated by Django 5.1.4 on 2025-02-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cupon_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positem',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='positem',
            name='product',
        ),
        migrations.DeleteModel(
            name='POS',
        ),
        migrations.DeleteModel(
            name='POSItem',
        ),
    ]
