# Generated by Django 5.1.4 on 2025-02-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_product_color_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
