# Generated by Django 5.1.4 on 2025-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_discount_order_shipping_cost_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], default='cod', max_length=20),
        ),
    ]
