# Generated by Django 5.1.4 on 2025-03-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_payment_status_order_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
