# Generated by Django 5.1.4 on 2025-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_cost_price_product_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
