# Generated by Django 5.1.4 on 2025-03-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_visitorsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorsession',
            options={'verbose_name': 'Visitor Session', 'verbose_name_plural': 'Visitor Sessions'},
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='user_agent',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorsession',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
