# Generated by Django 5.1.4 on 2025-03-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_visitorsession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salesrepresentativeprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='SalesRepresentativeProfile',
        ),
    ]
