# Generated by Django 5.1.4 on 2025-03-11 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_customerprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': '              Menu Items',
            },
        ),
        migrations.AlterModelOptions(
            name='cupon',
            options={'verbose_name': 'Cupon', 'verbose_name_plural': '                 Coupons'},
        ),
        migrations.AlterModelOptions(
            name='cuponapplied',
            options={'verbose_name': 'Cupon Applied', 'verbose_name_plural': '                Coupons Applied'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': '                     All Users'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.menuitem'),
        ),
    ]
