# Generated by Django 5.1.4 on 2025-03-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': '              Menu Item'},
        ),
    ]
