# Generated by Django 5.1.4 on 2025-03-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
    ]
