# Generated by Django 5.1.4 on 2025-03-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_color_size_tag_category_alter_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/images'),
            preserve_default=False,
        ),
    ]
