# Generated by Django 5.1.4 on 2025-03-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_session',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
