# Generated by Django 5.1.4 on 2025-02-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_positem_color_positem_size_alter_pos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
