# Generated by Django 5.1.4 on 2025-02-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_pos_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('due', 'Due')], default='pending', max_length=50),
        ),
    ]
