# Generated by Django 5.1.4 on 2025-03-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_pos_sub_total_alter_pos_discount_alter_pos_tax'),
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.color'),
        ),
        migrations.AlterField(
            model_name='positem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product'),
        ),
        migrations.AlterField(
            model_name='positem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.size'),
        ),
    ]
