# Generated by Django 5.1.4 on 2025-03-14 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_color_size_tag_category_alter_orderitem_color_and_more'),
        ('pos', '0007_alter_positem_color_alter_positem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.color'),
        ),
        migrations.AlterField(
            model_name='positem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='positem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.size'),
        ),
    ]
