# Generated by Django 5.1.4 on 2025-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetting',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter tax as a percentage (%)', max_digits=5, null=True),
        ),
    ]
