# Generated by Django 5.1.4 on 2025-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_companysetting_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysetting',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='companysetting',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
